FILENAME_BUILDNO = 'versioning'
FILENAME_VERSION_H = 'include/Version.h'
## EDIT THIS FILE FOR MAJOR AND MINOR VERSION, HOTFIX NUMBER IS IN THE versioning file
version = '2.0.'

import datetime

build_no = 0
try:
    with open(FILENAME_BUILDNO) as f:
        build_no = int(f.readline()) + 1
except:
    print('Starting build number from 1..')
    build_no = 1
with open(FILENAME_BUILDNO, 'w+') as f:
    f.write(str(build_no))
    print('Build number: {}'.format(build_no))

hf = """
// AUTO GENERATED FILE FROM buildscript_versioning.py, DO NOT EDIT THIS FILE
#ifndef BUILD_NUMBER
  #define BUILD_NUMBER "{}"
#endif
#ifndef VERSION
  #define VERSION "{} - {}"
#endif
#ifndef VERSION_SHORT
  #define VERSION_SHORT "{}"
#endif
""".format(build_no, version+str(build_no), datetime.datetime.now(), version+str(build_no))
with open(FILENAME_VERSION_H, 'w+') as f:
    f.write(hf)