light:
  - platform: mqtt
    schema: json
    name: "GlowWorm"
    state_topic: "lights/glowwormluciferin"
    command_topic: "lights/glowwormluciferin/set"
    effect: true
    effect_list:
      - GlowWorm
      - GlowWormWifi
      - bpm
      - rainbow
      - solid rainbow
      - mixed rainbow
      - solid
    brightness: true
    rgb: true
    optimistic: true
    #transition: 1000

input_select:
  gamma_select:
    name: "Gamma"
    options:
      - 1.0
      - 1.8
      - 2.0
      - 2.2
      - 2.4
      - 4.0
      - 5.0
      - 6.0
      - 8.0
      - 10.0
    initial: 2.2
    icon: mdi:gamma

input_number:
  pc_animation_speed:
    name: PC Animation Speed
    initial: 40
    min: 1
    max: 150
    step: 1

input_boolean:
  solideffect:
    name: Solid Effect
    initial: true
  solideffectautomation:
    name: Solid Effect Automation
    initial: false

sensor:
  - platform: mqtt
    state_topic: 'lights/firelyluciferin/framerate'
    name: 'Firefly Luciferin Producing'
    unit_of_measurement: 'FPS'
    value_template: '{{ value_json.producing }}'
  - platform: mqtt
    state_topic: 'lights/firelyluciferin/framerate'
    name: 'Firefly Luciferin Consuming'
    unit_of_measurement: 'FPS'
    value_template: '{{ value_json.consuming }}'
  - platform: mqtt
    state_topic: 'lights/glowwormluciferin'
    name: 'GlowWorm Version'
    unit_of_measurement: ' '
    value_template: '{{ value_json.ver }}'
    force_update: true
  - platform: mqtt
    state_topic: 'lights/glowwormluciferin'
    name: 'Glow Worm Luciferin FPS idle'
    unit_of_measurement: 'FPS'
    value_template: '{{ value_json.framerate }}'
  - platform: mqtt
    state_topic: 'lights/glowwormluciferin/fps'
    name: 'Glow Worm Luciferin FPS running'
    unit_of_measurement: 'FPS'
    value_template: '{{ value_json.framerate }}'
  - platform: template
    sensors:
      gw_fps:
        friendly_name: "Glow Worm Luciferin"
        value_template: >-
          {% if as_timestamp(states.sensor.glow_worm_luciferin_fps_idle.last_changed) > as_timestamp(states.sensor.glow_worm_luciferin_fps_running.last_changed) %}
            {{ states.sensor.glow_worm_luciferin_fps_idle.state }}
          {% else %}
            {{ states.sensor.glow_worm_luciferin_fps_running.state }}
          {% endif %}
        unit_of_measurement: 'FPS'
  - platform: mqtt
    state_topic: 'lights/glowwormluciferin'
    name: '# of LEDs'
    unit_of_measurement: ''
    value_template: '{{ value_json.lednum }}'
  - platform: mqtt
    state_topic: 'lights/glowwormluciferin'
    name: 'Last Update GlowWorm'
    value_template: '{{ as_timestamp(now()) | timestamp_custom("%Y-%m-%d ~ %H:%M:%S") }}'

automation:
  - id: '1548456985521'
    alias: Solid Effect ON
    trigger:
      - entity_id: input_boolean.solideffect
        from: 'off'
        platform: state
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.solideffectautomation
        state: 'off'
    action:
      - data:
          payload: '{"state":"ON","startStopInstances":"STOP"}'
          topic: lights/glowwormluciferin
        service: mqtt.publish
  - id: '1548456985522'
    alias: Solid effect OFF
    trigger:
      - entity_id: input_boolean.solideffect
        from: 'on'
        platform: state
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.solideffectautomation
        state: 'off'
    action:
      - data:
          payload: '{"state":"ON","startStopInstances":"PLAY"}'
          topic: lights/glowwormluciferin
        service: mqtt.publish

  - id: '3810295685522'
    alias: Solid Effect Auto
    trigger:
      - platform: time_pattern
        seconds: '/10'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.solideffectautomation
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ float(states.sensor.gw_fps.state) == 0 }}
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.solideffect
          - conditions:
              - condition: template
                value_template: >-
                  {{ float(states.sensor.gw_fps.state) > 0 }}
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.solideffect
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.solideffectautomation

  - id: '4321674486'
    alias: PC Animation Speed
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_number.pc_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: lights/glowwormluciferin/set
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
  - id: '1598969517535'
    alias: Glowworm Alive
    trigger:
      platform: time_pattern
      minutes: '/5'
    condition:
      condition: template
      value_template: "{{ (not (as_timestamp(now()) < (as_timestamp(states.sensor.glowworm_version.last_updated) + 300))) and (states.input_boolean.solideffect.state == 'on') }}"
    action:
      - data:
          message: "Glowworm stopped responding!"
        service: notify.telegram_notifier
  - id: '1598917385535'
    alias: Firefly Luciferin sensor reset
    trigger:
      - entity_id: switch.wake_on_lan
        from: 'on'
        platform: state
        to: 'off'
    action:
      - service: mqtt.publish
        data_template:
          topic: lights/firelyluciferin/framerate
          payload: '{"producing":0,"consuming":0}'
  - alias: Set Luciferin Gamma
    trigger:
      - entity_id: input_select.gamma_select
        platform: state
    action:
      - service: mqtt.publish
        data_template:
          topic: "lights/firelyluciferin/gamma"
          retain: "false"
          payload: '{"gamma":"{{states.input_select.gamma_select.state}}"}'
  - alias: Set HA Gamma
    trigger:
      platform: mqtt
      topic: "lights/firelyluciferin/gamma"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.gamma_select
        option: "{{ trigger.payload_json.gamma }}"

switch:
  - platform: mqtt
    name: "rebootglowworm"
    command_topic: "cmnd/glowwormluciferin/reboot"
    state_topic: "stat/glowwormluciferin/reboot"
    qos: 1
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
