
    // AUTO GENERATED FILE FROM version_increment.py, DO NOT EDIT THIS FILE
    #ifndef VERSION
      #define VERSION "3.4.3"
    #endif
    #ifndef BUILD_TIMESTAMP
      #define BUILD_TIMESTAMP "2020-05-10 23:29:56.085430"
    #endif
    