
    // AUTO GENERATED FILE FROM version_increment.py, DO NOT EDIT THIS FILE
    #ifndef VERSION
      #define VERSION "3.5.2"
    #endif
    #ifndef BUILD_TIMESTAMP
      #define BUILD_TIMESTAMP "2020-05-18 12:06:18.964881"
    #endif
    